### ISSUE TITLE
Core contract does not support external NFTs for bidding/selling

### ISSUE THREAD

**Issue by Timidan** [gyan0890/QLIP-App#2]
The core contract `QLIPMarketplaceWithBidding.sol` does not have a method that allow sellers to bring in their own NFTs for sale. i.e only Tokens created/minted on **Qlip** can be put up for sale/bidding .

This can be solved by removing the `nftAddress` as a constructor argument [here](https://github.com/gyan0890/QLIP-App/blob/a86ab30c8fd14a3ec8ff2ee647204e191a97766a/QLIPMarketplaceWithBidding.sol#L210) and setting it as an argument in another `listNFT` function...of course supported NFTs must be **whitelisted**

**Comment by gyan0890** [comment]
Updated the contracts and added them to the test branch. I have decoupled the NFT Minting and Flash selling contract from the auction contract.
